# Generated by Django 3.0.8 on 2020-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remoterequests', '0004_auto_20200714_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='test', unique=True),
        ),
    ]
